# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nominatim
email: nominatim@lonvia.de
description: Open source geocoding with OpenStreetMap data
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nominatim.org" # the base hostname & protocol for your site
github_username: "osm-search/Nominatim"

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
